name: CI (Windows)

on: [push]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin, ccl-bin]
        os: [windows-leatest]


    steps:
      - uses: actions/checkout@v1
      - name: Install roswell
        env:
          LISP: ${{ matrix.lisp }}
          ROSWELL_INSTALL_DIR: /c/roswell
        shell: bash
        run: |
          PATH="/c/roswell/bin:$PATH"
          curl -L https://raw.githubusercontent.com/fukamachi/roswell/windows-source-registry-settings/scripts/install-for-ci.sh | sh
      - name: Install ci-utils
        run: ros install ci-utils
      - name: Run 5am
        run: |
          PATH="~/.roswell/bin:/c/roswell/bin:$PATH"
          run-fiveam -l myapp/test myapp-test:myapp
