

name: CI

on: [push]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [windows-latest]

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
      - shell: msys2 {0}
        run: |
          makepkg-mingw -sCLfc --noconfirm --noprogressbar
          pacman --noconfirm -U mingw-w64-*-any.pkg.tar.xz
