# name: myapp

# on: [push]

# jobs:
#   test:
#     name: ${{ matrix.lisp }} on ${{ matrix.os }}
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         lisp: [sbcl-bin]
#         os: [macOS-latest, ubuntu-latest]

#     steps:
#       - uses: actions/checkout@v1
#       - name: Install Roswell
#         env:
#           LISP: ${{ matrix.lisp }}
#         run: |
#           curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
#       - name: Install ci-utils
#         run: ros install ci-utils
#       - name: Run 5am
#         run: |
#            PATH="~/.roswell/bin:$PATH"
#            run-fiveam -l myapp/test myapp-test:myapp

name: CI

on: [push]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-latest, macOS-latest, windows-2019]

    steps:
      - uses: actions/checkout@v1
      - uses: msys2/setup-msys2@v2
        if: matrix.os == 'windows-2019'
        with:
          msystem: MSYS
      - name: Install Roswell (Ubuntu & macOS)
        if: matrix.os != 'windows-2019'
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install Roswell (Windows)
        if: matrix.os == 'windows-2019'
        env:
          LISP: ${{ matrix.lisp }}
          ROSWELL_INSTALL_DIR: /c/roswell
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install ci-utils
        run: ros install ci-utils
      - name: Run tests (Ubuntu & macOS)
        if: matrix.os != 'windows-2019'
        run: |
          PATH="~/.roswell/bin:$PATH"
          run-fiveam -l myapp/test myapp-test:myapp
      - name: Run tests (Windows)
        if: matrix.os == 'windows-2019'
        run: |
          /c/roswell/bin/ros -S . -s fiveam -e '(asdf:test-system "myapp")'
